---
name: Tests

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          persist-credentials: false

      - name: Install Lua and LuaRocks
        run: sudo apt-get update && sudo apt-get install -y lua5.4 luarocks

      - name: Install Busted
        run: luarocks install busted

      - name: Run tests
        run: make test
