---
name: Tests

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          persist-credentials: false

      - name: Setup Mise
        uses: jdx/mise-action@4a894c31a8e098539d7713c3f6c6c2b4bf353ad7
        with:
          install: true

      - name: Install Busted
        run: mise run install

      - name: Run tests
        run: mise run test
